# Auth Events
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: auth-user-registered-subscription
spec:
  pubsubname: pubsub
  topic: auth.user.registered
  routes:
    default: /events/auth.user.registered
---
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: auth-email-verification-requested-subscription
spec:
  pubsubname: pubsub
  topic: auth.email.verification.requested
  routes:
    default: /events/auth.email.verification.requested
---
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: auth-password-reset-requested-subscription
spec:
  pubsubname: pubsub
  topic: auth.password.reset.requested
  routes:
    default: /events/auth.password.reset.requested
---
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: auth-password-reset-completed-subscription
spec:
  pubsubname: pubsub
  topic: auth.password.reset.completed
  routes:
    default: /events/auth.password.reset.completed
---
# User Events
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: user-created-subscription
spec:
  pubsubname: pubsub
  topic: user.created
  routes:
    default: /events/user.created
---
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: user-updated-subscription
spec:
  pubsubname: pubsub
  topic: user.updated
  routes:
    default: /events/user.updated
---
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: user-deleted-subscription
spec:
  pubsubname: pubsub
  topic: user.deleted
  routes:
    default: /events/user.deleted
---
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: user-email-verified-subscription
spec:
  pubsubname: pubsub
  topic: user.email.verified
  routes:
    default: /events/user.email.verified
---
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: user-password-changed-subscription
spec:
  pubsubname: pubsub
  topic: user.password.changed
  routes:
    default: /events/user.password.changed
---
# Order Events
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: order-placed-subscription
spec:
  pubsubname: pubsub
  topic: order.placed
  routes:
    default: /events/order.placed
---
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: order-cancelled-subscription
spec:
  pubsubname: pubsub
  topic: order.cancelled
  routes:
    default: /events/order.cancelled
---
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: order-delivered-subscription
spec:
  pubsubname: pubsub
  topic: order.delivered
  routes:
    default: /events/order.delivered
---
# Payment Events
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: payment-received-subscription
spec:
  pubsubname: pubsub
  topic: payment.received
  routes:
    default: /events/payment.received
---
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: payment-failed-subscription
spec:
  pubsubname: pubsub
  topic: payment.failed
  routes:
    default: /events/payment.failed
---
# Profile Events
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: profile-password-changed-subscription
spec:
  pubsubname: pubsub
  topic: profile.password_changed
  routes:
    default: /events/profile.password_changed
---
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: profile-notification-preferences-updated-subscription
spec:
  pubsubname: pubsub
  topic: profile.notification_preferences_updated
  routes:
    default: /events/profile.notification_preferences_updated
---
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: profile-bank-details-updated-subscription
spec:
  pubsubname: pubsub
  topic: profile.bank_details_updated
  routes:
    default: /events/profile.bank_details_updated
